config-version: 2

name: 'apple_store_source_integration_tests'
version: '0.1.0'

profile: 'integration_tests' 

vars:
  apple_store_source:
    apple_search_ads__using_subscriptions: true
    app: "{{ ref('app') }}"
    app_store_device_report: "{{ ref('app_store_source_type_device_report') }}"
    usage_device_report: "{{ ref('usage_source_type_device_report') }}"
    downloads_device_report: "{{ ref('downloads_source_type_device_report') }}"

    app_store_territory_report: "{{ ref('app_store_territory_source_type_report') }}"
    downloads_territory_report: "{{ ref('downloads_territory_source_type_report') }}"
    usage_territory_report: "{{ ref('usage_territory_source_type_report') }}"

    app_store_platform_version_report: "{{ ref('app_store_platform_version_source_type_report') }}"
    crashes_platform_version_device_report: "{{ ref('crashes_platform_version_device_report') }}"
    downloads_platform_version_report: "{{ ref('downloads_platform_version_source_type_report') }}"
    usage_platform_version_report: "{{ ref('usage_platform_version_source_type_report') }}"

    crashes_app_version_device_report: "{{ ref('crashes_app_version_device_report') }}"
    usage_app_version_report: "{{ ref('usage_app_version_source_type_report') }}"

    sales_account: "{{ ref('sales_account') }}"
    sales_subscription_event_summary: "{{ ref('sales_subscription_event_summary') }}"
    sales_subscription_summary: "{{ ref('sales_subscription_summary') }}"

seeds:
  +quote_columns: "{{ true if target.type == 'redshift' else false }}"
  apple_store_source_integration_tests:
      +column_types:
        _fivetran_synced: timestamp

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']