config-version: 2

name: 'apple_store_source_integration_tests'
version: '0.1.0'

profile: 'integration_tests' 

vars:
  apple_store_source:
    apple_store__using_subscriptions: true
    app: "{{ ref('app') }}"
    app_store_device: "{{ ref('app_store_source_type_device') }}"
    usage_device: "{{ ref('usage_source_type_device') }}"
    downloads_device: "{{ ref('downloads_source_type_device') }}"

    app_store_territory: "{{ ref('app_store_territory_source_type') }}"
    downloads_territory: "{{ ref('downloads_territory_source_type') }}"
    usage_territory: "{{ ref('usage_territory_source_type') }}"

    app_store_platform_version: "{{ ref('app_store_platform_version_source_type') }}"
    crashes_platform_version_device: "{{ ref('crashes_platform_version_device') }}"
    downloads_platform_version: "{{ ref('downloads_platform_version_source_type') }}"
    usage_platform_version: "{{ ref('usage_platform_version_source_type') }}"

    crashes_app_version_device: "{{ ref('crashes_app_version_device') }}"
    usage_app_version: "{{ ref('usage_app_version_source_type') }}"

    sales_account: "{{ ref('sales_account') }}"
    sales_subscription_events: "{{ ref('sales_subscription_events') }}"
    sales_subscription_summary: "{{ ref('sales_subscription_summary') }}"

seeds:
  apple_store_source_integration_tests:
      +quote_columns: "{{ true if target.type == 'redshift' else false }}"
      +column_types:
        _fivetran_synced: timestamp
        date: timestamp

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']